on: [push]

name: Atlas CLI Action Sample

jobs:
  use-atlas-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup AtlasCLI
        uses: mongodb/atlas-github-action@CLOUDP-202471
      - name: Print env var
        shell: bash
        run: |
          # define variables      
          tests=16

          # set them as GitHub ENV variables
          echo "Tests=$tests" >> $GITHUB_ENV

          # retrieve these GitHub ENV variables
          echo "${{ env.Tests }} on CI"
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version # Print Atlas CLI Version
