on: [push]

name: Atlas CLI Action Sample

env:
  MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
  MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }} # default organisation ID
  MONGODB_ATLAS_PROJECT_ID: ${{ secrets.PROJECT_ID }} # default project ID
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install AtlasCLI
        id: install
        uses: mongodb/atlas-github-action@temp/test-atlas-is-containerized
      - name: Create a Project
        id: create-project
        shell: bash
        run: |
          projectId=$(atlas project create test-setup-project -o json-path="$.id")
          echo "create-project-id=$(echo $projectId)" >> $GITHUB_OUTPUT
      - name: Run setup
        id: setup
        uses: mongodb/atlas-github-action@temp/test-atlas-is-containerized
        with:
          run-setup: true
          project-id: ${{ steps.create-project.outputs.create-project-id }}
          cluster-name: GH-action-determine-tag
          username: test-user
          password: test-password
      - name: Retrieve Connection String
        shell: bash
        run: |
          echo "${{ steps.setup.outputs.connection-string }}"
      - name: Teardown
        uses: mongodb/atlas-github-action@temp/test-atlas-is-containerized
        with:
          delete-project-id: ${{ steps.create-project.outputs.create-project-id }}
          delete-cluster-name: GH-action-determine-tag
